<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260916143506 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE competence (id_competence INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, libelle VARCHAR(100) NOT NULL, PRIMARY KEY (id_competence))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_94D4687FA4D60759 ON competence (libelle)');
        $this->addSql('CREATE TABLE salarie (id_salarie INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(50) NOT NULL, prenom VARCHAR(50) NOT NULL, civilite VARCHAR(8) NOT NULL, email VARCHAR(150) NOT NULL, telephone VARCHAR(20) DEFAULT NULL, adresse VARCHAR(150) DEFAULT NULL, code_postal VARCHAR(10) DEFAULT NULL, ville VARCHAR(50) DEFAULT NULL, id_site INT NOT NULL, PRIMARY KEY (id_salarie))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_828E3A1AE7927C74 ON salarie (email)');
        $this->addSql('CREATE INDEX IDX_828E3A1AE26315E6 ON salarie (id_site)');
        $this->addSql('CREATE TABLE posseder (id_salarie INT NOT NULL, id_competence INT NOT NULL, PRIMARY KEY (id_salarie, id_competence))');
        $this->addSql('CREATE INDEX IDX_62EF7CBA5C13936A ON posseder (id_salarie)');
        $this->addSql('CREATE INDEX IDX_62EF7CBA315EE8A8 ON posseder (id_competence)');
        $this->addSql('CREATE TABLE site (id_site INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom_site VARCHAR(100) NOT NULL, PRIMARY KEY (id_site))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_694309E49B93C38A ON site (nom_site)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE salarie ADD CONSTRAINT FK_828E3A1AE26315E6 FOREIGN KEY (id_site) REFERENCES site (id_site) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE posseder ADD CONSTRAINT FK_62EF7CBA5C13936A FOREIGN KEY (id_salarie) REFERENCES salarie (id_salarie) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE posseder ADD CONSTRAINT FK_62EF7CBA315EE8A8 FOREIGN KEY (id_competence) REFERENCES competence (id_competence) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE salarie DROP CONSTRAINT FK_828E3A1AE26315E6');
        $this->addSql('ALTER TABLE posseder DROP CONSTRAINT FK_62EF7CBA5C13936A');
        $this->addSql('ALTER TABLE posseder DROP CONSTRAINT FK_62EF7CBA315EE8A8');
        $this->addSql('DROP TABLE competence');
        $this->addSql('DROP TABLE salarie');
        $this->addSql('DROP TABLE posseder');
        $this->addSql('DROP TABLE site');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
